### ISSUE TITLE
关于商店购买东西出错

### ISSUE THREAD

**Issue by Autumn-Official** [jiellll1219/OpenDoctoratePy-EX-Public#2]
我尝试着将shop和pay相关的代码铐下来缝到我odpy里用，缝完之后商店是能进了，但是在购买物品方面好像有问题，组合包及源石交易所会弹网络404，这个倒是无伤大雅，但是在绿票黄票商店的购买部分会有问题，会报错误500，
![image (1)](https://github.com/user-attachments/assets/5d8f9acd-3f6a-4630-bf6e-31ed345d596d)
![image (2)](https://github.com/user-attachments/assets/2ecd2351-ac4d-48d6-99b5-101ed0d88b21)
报错发生在shop.py的126行，貌似是索引的问题，字符串的索引只能是数字，不能是字符串

**Comment by jiellll1219** [comment]
已在 [aa5e810](https://github.com/jiellll1219/OpenDoctoratePy-EX-Public/commit/aa5e810e607ddfd9ab765ef02dcd119ba22365a2) 中修复该问题

**Comment by jiellll1219** [comment]
关于组合包与源石部分的补充：
由于我是完全不充钱的玩家，所以我无法抓取与充值相关的数据，实现该部分的代码参考了LocalArknight
