### ISSUE TITLE
这个服务端有使用教程吗?

### ISSUE THREAD

**Issue by tb114514** [jiellll1219/OpenDoctoratePy-EX-Public#3]
我克隆仓库打开bat之后提示我:
![捕获](https://github.com/user-attachments/assets/1e22e6bf-ffa3-4a37-a48e-6e3a1cb11f21)
我安装完Crypto后依旧是这个报错

**Comment by jiellll1219** [comment]
此仓库的bat使用env环境，请在env环境中安装缺少的内容。
亦可复制其它仓库的env环境进行使用，该仓库的依赖项与源项目一致。
短期内我并没有计划去制作一份使用教程，我认为该python项目的使用是非常简单的。
如果需要使用教程，请参考其它OpenDoctoratePy仓库的README。

**Comment by tb114514** [comment]
> 此仓库的bat使用env环境，请在env环境中安装缺少的内容。 可以复制仓库的env环境进行使用，该仓库的依赖项与源项目一致。 短期内我并没有计划制作其他一个去使用教程，我认为该python项目的使用是非常简单的。 如果需要使用教程，请参考其他OpenDoctoratePy仓库的README。

好的我试试

**Comment by tb114514** [comment]
> 此仓库的bat使用env环境，请在env环境中安装缺少的内容。 可以复制仓库的env环境进行使用，该仓库的依赖项与源项目一致。 短期内我并没有计划制作其他一个去使用教程，我认为该python项目的使用是非常简单的。 如果需要使用教程，请参考其他OpenDoctoratePy仓库的README。

我去原版的OpenDoctoratePy搞了一个，都弄好以后启用start_frida-hook.bat模拟器启动游戏以后一到加载网络配置就闪退,控制台输出:
127.0.0.1 - - [28/Aug/2024 23:51:04] "GET /config/prod/official/network_config?sign=1724860264%20234586912%20334994 HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2024 23:51:04] "GET /config/prod/official/remote_config HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2024 23:51:04] "GET /app/v1/config?appCode=7318def77669979d HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2024 23:51:04] "GET /general/v1/server_time HTTP/1.1" 200 -
咋解决呀?

**Comment by tb114514** [comment]
> 此仓库的bat使用env环境，请在env环境中安装缺少的内容。 可以复制仓库的env环境进行使用，该仓库的依赖项与源项目一致。 短期内我并没有计划制作其他一个去使用教程，我认为该python项目的使用是非常简单的。 如果需要使用教程，请参考其他OpenDoctoratePy仓库的README。

我想问几个问题,可以的话谢谢帮忙解答!这个仓库里的东西是直接用还是覆盖掉原来odpy仓库里的文件?游戏是使用最新的吗?需不需要先吧游戏里的7个G给他先下载完?

我用原来的服务端可以正常启动，守护者进程也能启动,雷电mumu都可以，然后启用hook注入的时候，雷电是过完开头动画到加载网络配置直接闪退，mumu是可以不闪退但是显示无法连接至网络。

此仓库的东西覆盖掉回报错:
Traceback (most recent call last):
  File "D:\Desktop\mrfzsf\OpenDoctorate-auto\server\app.py", line 88, in <module>
    app.add_url_rule('/pay/getUnconfirmedOrderIdList', methods=['POST'], view_func=pay.payGetUnconfirmedOrderIdList)

AttributeError: module 'pay' has no attribute 'payGetUnconfirmedOrderIdList'. Did you mean: 'GetUnconfirmedOrderIdList'?

直接使用此仓库会报错缺少json

**Comment by jiellll1219** [comment]
1、请仔细阅读README。
2、客户端问题请自行解决。
此仓库不负责解答与处理任何部署、使用问题，只确保代码可用，请动动你那聪明的大脑，把此仓库的代码与源项目进行缝合。这些门槛只是为了防止泛滥与倒卖

**Comment by tb114514** [comment]
> 1、请仔细阅读README。 2、客户端问题请自行解决。 此仓库不负责解答与处理任何部署、使用问题，只确保代码可用，请动动你那聪明的大脑，把此仓库的代码与源项目进行缝合。这些门槛只是为了防止泛滥与倒卖

真的不知道怎么解决了......想了很久也试了很久

**Comment by tb114514** [comment]
用的sakurasep/OpenDoctorate的服务端，我也试了试吧冷权的2.1.01替换掉了data和config,结果获取两个请求就闪退了...
直接用冷权的2.1.01的客户端和2.1.01的游戏确实可以打开进去。我也不知道找谁解决这个直接退出的问题

**Comment by tb114514** [comment]
用的sakurasep/OpenDoctorate的服务端，我也试了试吧冷权的2.1.01替换掉了data和config,结果获取两个请求就闪退了...
直接用冷权的2.1.01的客户端和2.1.01的游戏确实可以打开进去。我也不知道找谁解决这个直接退出的问题

**Comment by jiellll1219** [comment]
此问题属于客户端问题，本仓库不会提供任何与客户端相关的内容与帮助，请自行解决
